name: Elixir Dialyzer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dialyzer:

    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15'
        otp-version: '26'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: |
          deps
          _build
        key: dialyzer-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

    - name: Install dependencies
      run: mix deps.get

    - run: mix dialyzer
