name: Elixir CI

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.2"
          otp-version: "23.1.2"
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
      - name: Check format
        run: mix format --check-formatted
