name: Elixir CI

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir-version: ["1.16"]
        otp-version: ["25", "26"]
        include:
          - elixir-version: "1.15"
            otp-version: "25"
          - elixir-version: "1.14"
            otp-version: "25"
          - elixir-version: "1.13"
            otp-version: "24"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}

      - name: Install dependencies
        run: mix deps.get
      - name: Compile deps
        run: MIX_ENV=test mix deps.compile
      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run tests
        run: mix test --warnings-as-errors
      - name: Run integration tests
        env:
          ELIXIR_SANITY_TEST_PROJECT_ID: ${{ secrets.ELIXIR_SANITY_TEST_PROJECT_ID }}
          ELIXIR_SANITY_TEST_TOKEN: ${{ secrets.ELIXIR_SANITY_TEST_TOKEN }}
        if: env.ELIXIR_SANITY_TEST_TOKEN
        run: mix test --warnings-as-errors --only integration
      - name: Check format
        run: mix format --check-formatted
